### ISSUE TITLE
Publication Link not matching Repo Link

### ISSUE THREAD

**Issue by nerffan1** [FLOSIC/si_magentic_exchange_coupling#1]
Hello,

The [publication](https://pubs.acs.org/doi/10.1021/acs.jpca.1c10354) has the link `https://github.com/FLOSIC/si_magnetic_exchange_coupling`, however the Repo has a typo: _magentic_ instead of _magnetic_

**Comment by FLOSIC** [comment]
Thanks! It is corrected.
